# Generated by Django 3.2.9 on 2021-12-01 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0002_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TotalPay',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.AddField(
            model_name='order',
            name='order_timedate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='order',
            name='totalPay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.item')),
            ],
        ),
    ]
