# Generated by Django 3.2.9 on 2021-12-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0005_auto_20211201_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_date',
            field=models.DateTimeField(),
        ),
    ]
