# Generated by Django 3.2.9 on 2021-12-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0008_auto_20211202_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='../static/anonymous.jpg', upload_to='uploads'),
        ),
    ]
