# Generated by Django 3.2.9 on 2021-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='../static/img/anonymous.jpg', upload_to='uploads'),
        ),
    ]
