# Generated by Django 3.2.9 on 2021-12-02 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0011_alter_orderitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 17, 1, 6, 249502)),
        ),
    ]
