# Generated by Django 3.2.9 on 2021-12-06 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0014_auto_20211206_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 16, 25, 32, 522026)),
        ),
    ]
