# Generated by Django 3.2.9 on 2021-12-07 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0015_alter_order_order_time_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_persons', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 12, 57, 22, 782908)),
        ),
        migrations.DeleteModel(
            name='redirect',
        ),
    ]
