# Generated by Django 3.2.9 on 2021-12-10 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0019_auto_20211208_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('coffee', 'coffee'), ('softdrinks', 'softdrinks'), ('snacks', 'snacks'), ('snacks', 'tea')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 11, 25, 19, 20618)),
        ),
    ]
