# Generated by Django 3.2.9 on 2021-12-29 07:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0020_auto_20211210_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='availability',
            field=models.CharField(choices=[('pending', 'pending'), ('available', 'available'), ('not_available', 'not_available')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('coffee', 'coffee'), ('softdrinks', 'softdrinks'), ('snacks', 'snacks'), ('tea', 'tea')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 9, 4, 33, 743850)),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
