# Generated by Django 3.2.9 on 2022-01-04 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0021_auto_20211229_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='availability',
            field=models.CharField(choices=[('pending', 'pending'), ('available', 'available'), ('not_available', 'not_available')], default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='table',
            name='requested_on',
            field=models.DateField(default=datetime.date(2022, 1, 4)),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='time_needed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 16, 47, 21, 449240)),
        ),
    ]
